version: '3'
services:
  test-redis:
    image: redis
  test-postgres:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=storj
    - POSTGRES_PASSWORD=storj-pass
    - POSTGRES_DB=teststorj

  satellite:
    image: storjlabs/satellite:${VERSION:-latest}
    environment:
    - API_KEY=abc123
    - STORJ_CHECKER_QUEUE_ADDRESS=redis://redis:6379/?db=0
    - STORJ_DATABASE=postgres://postgres:postgres@postgres/satellite?sslmode=disable
    - STORJ_LOG_LEVEL=debug
    - STORJ_REPAIRER_QUEUE_ADDRESS=redis://redis:6379/?db=0
    - STORJ_IDENTITY_SERVER_ADDRESS=satellite:7777
    restart: always
    ports:
    - 7778:7777
    links:
    - redis
    - postgres
    depends_on:
    - redis
    - postgres
  storagenode:
    image: storjlabs/storagenode:${VERSION:-latest}
    environment:
    - SATELLITE_ADDR=satellite:7777
    - STORJ_KADEMLIA_EXTERNAL_ADDRESS=storagenode:7777
    - STORJ_KADEMLIA_OPERATOR_EMAIL=hello@storj.io
    - STORJ_KADEMLIA_OPERATOR_WALLET=0x0000000000000000000000000000000000000000
    - STORJ_LOG_LEVEL=debug
    restart: always
    links:
    - satellite
  gateway:
    image: storjlabs/gateway:${VERSION:-latest}
    command: --rs.min-threshold 1 --rs.max-threshold 1 --rs.repair-threshold 1 --rs.success-threshold 1
    environment:
    - API_KEY=abc123
    - SATELLITE_ADDR=satellite:7777
    - STORJ_LOG_LEVEL=debug
    - STORJ_SERVER_ADDRESS=0.0.0.0:7777
    ports:
    - 7777:7777
    restart: always
    links:
    - satellite
    - storagenode
  redis:
    image: redis
  postgres:
    image: postgres:11.1
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=satellite
